"""Anthropic Claude implementation of LLMProvider (default provider)."""
import logging

import anthropic

from app.minutes.providers.base import LLMError, LLMProvider, LLMResult

logger = logging.getLogger(__name__)

# Server-side fallback: if Claude's safety classifiers decline a request, the API re-runs
# it on Anthropic's recommended fallback model inside the same call.
FALLBACK_BETA = "server-side-fallback-2026-07-01"

# The SDK raises a bare TypeError at request time when no API key / auth token / profile is found.
_NO_CREDENTIALS = "Could not resolve authentication method"


def _is_missing_credentials(exc: TypeError) -> bool:
    return _NO_CREDENTIALS in str(exc)


class AnthropicProvider(LLMProvider):
    name = "anthropic"

    def __init__(self, *, model: str, api_key: str | None = None, effort: str = "high",
                 max_output_tokens: int = 32000, fallbacks: bool = True, client=None):
        self._model = model
        self._effort = effort
        self._max_output_tokens = max_output_tokens
        self._fallbacks = fallbacks
        self._api_key = api_key or None  # None -> SDK resolves env var / `ant auth login` profile
        self._client = client

    def _get_client(self):
        if self._client is None:
            try:
                self._client = anthropic.Anthropic(api_key=self._api_key)
            except anthropic.AnthropicError as exc:
                raise LLMError("not_configured", str(exc)) from exc
        return self._client

    def generate(self, system: str, user_content: str) -> LLMResult:
        extra = {"betas": [FALLBACK_BETA], "fallbacks": "default"} if self._fallbacks else {}
        try:
            # Streaming: minutes for a long meeting can take minutes to write; a non-streaming
            # request with a large max_tokens risks HTTP timeouts.
            with self._get_client().beta.messages.stream(
                model=self._model,
                max_tokens=self._max_output_tokens,
                system=system,
                messages=[{"role": "user", "content": user_content}],
                thinking={"type": "adaptive"},
                output_config={"effort": self._effort},
                **extra,
            ) as stream:
                message = stream.get_final_message()
                # Streamed messages carry no `_request_id`; the ID is on the stream's response headers.
                request_id = stream.request_id
        except anthropic.AuthenticationError as exc:
            raise LLMError("auth_failed", exc.message) from exc
        except anthropic.PermissionDeniedError as exc:
            raise LLMError("auth_failed", exc.message) from exc
        except anthropic.RateLimitError as exc:
            raise LLMError("rate_limited", exc.message) from exc
        except anthropic.BadRequestError as exc:
            raise LLMError("bad_request", exc.message) from exc
        except anthropic.APIStatusError as exc:
            code = "provider_unavailable" if exc.status_code >= 500 else "bad_request"
            raise LLMError(code, f"{exc.status_code} {exc.message}") from exc
        except anthropic.APIConnectionError as exc:
            raise LLMError("connection_failed", str(exc)) from exc
        except anthropic.AnthropicError as exc:
            raise LLMError("not_configured", str(exc)) from exc
        except TypeError as exc:
            if _is_missing_credentials(exc):
                raise LLMError("not_configured", "no Anthropic credentials (set ANTHROPIC_API_KEY)") from exc
            raise

        logger.info("minutes generated by %s (request %s)", message.model, request_id)
        if message.stop_reason == "refusal":
            category = getattr(message.stop_details, "category", None) if message.stop_details else None
            raise LLMError("refused", f"category={category}")
        if message.stop_reason == "max_tokens":
            raise LLMError("truncated", f"output exceeded max_tokens={self._max_output_tokens}")

        text = "".join(block.text for block in message.content if block.type == "text").strip()
        return LLMResult(
            text=text,
            model=message.model,
            input_tokens=message.usage.input_tokens,
            output_tokens=message.usage.output_tokens,
        )

    def count_tokens(self, system: str, user_content: str) -> int | None:
        try:
            result = self._get_client().messages.count_tokens(
                model=self._model,
                system=system,
                messages=[{"role": "user", "content": user_content}],
            )
            return result.input_tokens
        except (anthropic.AnthropicError, LLMError):
            logger.warning("count_tokens failed; falling back to a length estimate", exc_info=True)
            return None
        except TypeError as exc:
            if _is_missing_credentials(exc):
                return None  # generate() will report not_configured
            raise
